name: ayup CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 12.14.1
      - name: Installing Dependencies
        run: npm ci --quiet --no-progress
      - name: Building
        run: npm run build
      - name: Testing & Certifying
        run: npm run ci
